# Beeminder credentials
beeminder_username = "your_username"
beeminder_key = { env = "BEEMINDER_API_KEY" }
# Alternative: beeminder_key = { cmd = "cat ~/.beeminder_key" }

# [clean_tube]
# activity_watch_base_url = "http://localhost:5600"
# window_bucket = "aw-watcher-window_laptop"
# goal_name = "youtube"
# lookback_days = 7
# min_video_duration_seconds = 60.0
# max_datapoints = 100

# [focusmate]
# key = { env = "FOCUSMATE_API_KEY" }
# # Alternative: key = { cmd = "cat ~/.focusmate_key" }
# goal_name = "focusmate"
# auto_tags = ["work", "coding", "writing"]

# [fatebook]
# key = { env = "FATEBOOK_API_KEY" }
# # Alternative: key = { cmd = "keyring get fatebook-api-key me" }
