# Beeminder credentials
beeminder_username = "your_username"
beeminder_key = { env = "BEEMINDER_API_KEY" }
# Alternative: beeminder_key = { cmd = "cat ~/.beeminder_key" }

# [clean_tube]
# activity_watch_base_url = "http://localhost:5600"
# window_bucket = "aw-watcher-window_laptop"
# goal_name = "youtube"
# lookback_days = 7
# min_video_duration_seconds = 60.0
# max_datapoints = 100

# [focusmate]
# key = { env = "FOCUSMATE_API_KEY" }
# # Alternative: key = { cmd = "cat ~/.focusmate_key" }
# goal_name = "focusmate"
# auto_tags = ["work", "coding", "writing"]

# [fatebook]
# key = { env = "FATEBOOK_API_KEY" }
# # Alternative: key = { cmd = "keyring get fatebook-api-key me" }

# [category]
# uri = { env = "AMAZING_MARVIN_URI" }
# username = { env = "AMAZING_MARVIN_USERNAME" }
# password = { env = "AMAZING_MARVIN_PASSWORD" }
# database_name = { env = "AMAZING_MARVIN_DATABASE" }
# # Alternative: uri = { cmd = "keyring get amazing-marvin-uri me" }
# # Alternative: username = { cmd = "keyring get amazing-marvin-username me" }
# # Alternative: password = { cmd = "keyring get amazing-marvin-password me" }
# # Alternative: database_name = { cmd = "keyring get amazing-marvin-database me" }
# category = "Must Do"
# goal_name = "tasks"

# [clean_view]
# activity_watch_base_url = "http://localhost:5600"
# window_bucket = "aw-watcher-window_laptop"
# goal_name = "social-media"
# lookback_days = 3
# openai_key = { env = "OPENAI_API_KEY" }
# # Alternative: openai_key = { cmd = "cat ~/.openai_key" }
# openai_model = "gpt-4o"
# min_window_duration_seconds = 10.0
# prompt_template = """
# I have a goal to reduce my social media usage. Please analyze the following window titles 
# and determine if any indicate social media usage (Facebook, Twitter/X, Instagram, TikTok, 
# Reddit, LinkedIn, etc.).
# 
# Either reply:
# 
# no
# 
# Or:
# 
# yes
# <list the social media window titles here, one per line>
# 
# Make sure you list only the lines that definitely indicate social media usage.
# If there aren't any social media titles, just reply 'no' without quotes.
# 
# Titles:
# {{titles}}
# """
